### ISSUE TITLE
Tutorial not working?

### ISSUE THREAD

**Issue by dgkurt** [lmc297/BTyper3#9]
ANI seems not to be working for me. Using the tutorial data, I got the attached results, with no ANI classification. I also attach the log.
I tried a few genomes but never got an ANI classification, even with the "--ani_typestrains" True parameter  
[JHQN01.1.log](https://github.com/lmc297/BTyper3/files/9796857/JHQN01.1.log)
[JHQN01.1_final_results.txt](https://github.com/lmc297/BTyper3/files/9796858/JHQN01.1_final_results.txt)

**Comment by althonos** [comment]
Hi @dgkurt, thanks for your report, I have found the bug causing this in the `btyper3.ani` module and will make a new release shortly.

**Comment by althonos** [comment]
This is now fixed in `v3.3.3`, please try again after updating :wink: :
